# Generated by Django 2.0.5 on 2019-05-21 12:57

from django.db import migrations, models
import resume.models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.FileField(blank=True, upload_to=resume.models.user_directory_path, verbose_name='模板文件'),
        ),
    ]
