# Generated by Django 2.0.5 on 2019-05-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='kind',
            field=models.SmallIntegerField(choices=[(0, '学生'), (1, '教师')], default=0, verbose_name='种类'),
        ),
    ]
